apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloweb
  name: helloweb
spec:
  ports:
  - port: 85
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloweb
  type: NodePort
status:
  loadBalancer: {}
